services:
  dev:
    build:
      context: docker/dev
    volumes:
      - ..:/workspace
      - pet-data:/data
    working_dir: /workspace
    stdin_open: true
    tty: true

  labelstudio:
    extends:
      file: docker/labelstudio/docker-compose.yml
      service: labelstudio
    depends_on:
      labelstudio-db:
        condition: service_healthy

  labelstudio-db:
    extends:
      file: docker/labelstudio/docker-compose.yml
      service: labelstudio-db

volumes:
  pet-data:
  labelstudio-data:
  labelstudio-pg:
